### PR TITLE
fix sending evm tx with Acala

### PR DESCRIPTION
**Pull request by shunjizhan**
## Change
Currently when sending acala evm tx, talisman will throw [tx hash mismatch](https://evmdocs.acala.network/~/revisions/MXz2qzO0RKq12hRqR5B7/miscellaneous/common-errors#transaction-hash-mismatch-from-provider.sendtransaction) error.

This commit switches to `AcalaJsonRpcProvider` for Acala network family, which solves the above issue

## Test
- built the wallet locally, and tried sending an Acala evm tx, which succeed and didn't throw `tx hash mismatch` anymore
- all CI tests passed

### CODE REVIEW

**Comment by shunjizhan** [comment]
ummmm it seems there are some compatibility issue, let me take a look into this, will update the PR soon

**Comment by shunjizhan** [comment]
@alecdwm previous issue was that jest didn't seem to respect `exports` field in `package.json`, [this exports](https://github.com/ReactiveX/rxjs/blob/7.x/package.json#L60-L65)  in particular. So I had to manually add the path resolve rule for it, so jest can find this module

Now running `yarn test` locally passed for me, can you trigger the CI to try again? Thanks!

**Comment by alecdwm** [comment]
Thanks for the PR! And for the jest fix 🎉 

We're just about to release v1.19.0 after some extended testing, so it's unlikely this will make it into that release. But I've heard the plan is to include this PR in a hotfix once we're done with that

Edit:

You can ignore that `Talisman CI / Publish a snapshot version...` CI check, it shouldn't be running here anyway

**Comment by shunjizhan** [comment]
> But I've heard the plan is to include this PR in a hotfix once we're done with that

sounds awesome! Thanks a lot

**Review by chidg — APPROVED** [review]
LGTM

**Review by chidg — CHANGES_REQUESTED** [review]
Thanks for the PR - thought it was good to go however I will have to change my review after further testing
When testing, I found that this PR doesn't work with Talisman's send funds UI when sending Acala substrate assets. The user can't progress to the 'Review' stage, probably because some awaited request has not resolved. The current dev branch is able to send Acala assets in the same way. I wasn't able to dig into the reason. Could you please look into this?

**Comment by shunjizhan** [comment]
@chidg thanks for your review, I tried sending ACA on the substrate side with locally built talisman on this branch, and it worked for me. I was not blocked on the review page, and the tx actually [went through](https://acala.subscan.io/tx/0xb379f5375ef6cd0fc7d16042d3639367e7b232cb948b0251fbcbb92fb053bd16). 

Were you sending any other assets? Could this happened to be your network issue?
 
Screenshot 2023-10-10 at 16 43 27
Screenshot 2023-10-10 at 16 43 35
Screenshot 2023-10-10 at 16 43 49

**Comment by shunjizhan** [comment]
also tried sending dot on Acala, and didn't see any issue 
Screenshot 2023-10-10 at 16 50 54
Screenshot 2023-10-10 at 16 51 02
Screenshot 2023-10-10 at 16 51 53

**Comment by shunjizhan** [comment]
hey @chidg, any updates on this? Please let me know if there is anything else I can help

**Comment by chidg** [comment]
Thanks @shunjizhan , I have been AFK for the past couple of weeks. Will have another look this week.

**Review by chidg — APPROVED** [review]
Works well, thanks for the neat PR @shunjizhan and apologies for the delay in approving.
LGTM!

**Comment by shunjizhan** [comment]
Thanks @chidg! Please keep me updated once this is included in the release

**Pull request merged**
