### PR TITLE
fix: update caniuse-lite

### PR DESCRIPTION
**Pull request by alecdwm**
Version `1.0.30001409` is a year old

### CODE REVIEW

**Review by 0xKheops — COMMENTED** [review]
agree it feels necessary, but unsure about the mechanism that was used to update the yarn lock like this

what about bumping autoprefixer ? 
it is one of our dependencies, being a TW's prerequisite, it's in charge of css generation with the correct browser css prefixes.
if upgrading it from 10.4.12 to 10.4.15, it would upgrade caniuse-lite to  1.0.30001520

**Comment by 0xKheops** [comment]
just noticed the message when building, was it a `npx update-browserslist-db@latest` ?

**Comment by alecdwm** [comment]
It was!

**Review by 0xKheops — APPROVED** [review]
LGTM!

**Pull request merged**
